apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  namespace: first-namespace
spec:
  containers:
  - name: first-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
